# 01 — PyTorch Tensors: Basics
PyTorch is a deep learning framework, and the most fundamental object in PyTorch is the **Tensor**.

Almost everything we use in deep learning is represented using tensors:

- Input data
- Images
- Labels
- Model parameters
- Weights
- Biases
- Predictions
- Gradients
     
Before learning neural networks, we need to become very comfortable working with tensors.

## In this notebook, we will learn:

1. What a tensor is
2. Scalars, vectors, matrices, and higher-dimensional tensors
3. Tensor shape
4. Tensor dimensions
5. Number of elements
6. Tensor data types
7. Creating tensors
8. Random tensors
9. Tensor devices
10. Basic tensor inspection

The main goal is to understand how PyTorch represents data.

In [1]:
import torch

print("PyTorch version:", torch.__version__)

PyTorch version: 2.11.0+cpu


## 1. What is a Tensor?

A **tensor** is a container that stores numbers.

A tensor can have different numbers of dimensions.

For example:

- A single number → Scalar
- A list of numbers → Vector
- A table of numbers → Matrix
- Multiple matrices → Higher-dimensional tensor

Tensors are similar to NumPy arrays, but PyTorch tensors have additional features that are useful for deep learning.

Later, tensors can:

- Run on GPUs
- Track gradients automatically
- Store neural-network parameters
- Participate in automatic differentiation

## 2. Scalar

A scalar is a **single number**.

Examples:

$$
\boxed{5}
\qquad
\boxed{3.14}
\qquad
\boxed{-20}
$$

A scalar has **zero dimensions**.

In [2]:
scalar = torch.tensor(5)

print(scalar)

tensor(5)


In [3]:
print("Number of dimensions:", scalar.ndim)

print("Shape:", scalar.shape)

Number of dimensions: 0
Shape: torch.Size([])


### Understanding the result

The scalar contains only one value.

Its number of dimensions is: 0

Therefore, a scalar is called a **0-dimensional tensor**.

## 3. Vector

A vector is a **one-dimensional collection of numbers**.

Example:
$$
\begin{array}{|c|c|c|}
\hline
10 & 20 & 30 \\
\hline
\end{array}
$$

A vector has one dimension.

In [4]:
vector = torch.tensor([10, 20, 30])

print(vector)

tensor([10, 20, 30])


In [5]:
print("Shape:", vector.shape)
print("Dimensions:", vector.ndim)
print("Number of elements:", vector.numel())

Shape: torch.Size([3])
Dimensions: 1
Number of elements: 3


### Understanding the shape

The shape is: [3]

This tells us that the tensor contains 3 values along its only dimension.

Therefore:

- Dimensions = 1
- Number of elements = 3

## 4. Matrix

A matrix is a **two-dimensional collection of numbers**.

A matrix contains rows and columns.

Example:

$$
\begin{array}{|c|c|c|}
\hline
1 & 2 & 3 \\
\hline
4 & 5 & 6 \\
\hline
\end{array}
$$

This matrix has:

- 2 rows
- 3 columns

Therefore its shape is: [2, 3]

In [7]:
matrix = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [8]:
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Number of elements:", matrix.numel())

Shape: torch.Size([2, 3])
Dimensions: 2
Number of elements: 6


### Understanding the result

The shape is:

[2, 3]

This means:

- 2 rows
- 3 columns

The tensor has 2 dimensions.

The total number of elements is:

2 × 3 = 6

## 5. Three-Dimensional Tensor

Tensors are not limited to rows and columns.

We can also have tensors with three or more dimensions.

One way to imagine a 3D tensor is:

> A collection of matrices.

In [9]:
tensor_3d = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
print(tensor_3d)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


In [10]:
print("Shape:", tensor_3d.shape)
print("Dimensions:", tensor_3d.ndim)
print("Number of elements:", tensor_3d.numel())

Shape: torch.Size([2, 2, 3])
Dimensions: 3
Number of elements: 12


### Understanding the shape

The shape is:

[2, 2, 3]

We can interpret this as:

- 2 blocks
- 2 rows inside each block
- 3 values inside each row

Total elements:

2 × 2 × 3 = 12

# 6. Important Tensor Properties

There are several properties that we will use constantly when working with PyTorch.

The most important are:

### `tensor.shape`

Tells us the size of each dimension.

### `tensor.ndim`

Tells us how many dimensions the tensor has. ### `tensor.numel()` Tells us the total number of elements.

### `tensor.dtype`

Tells us the data type.

### `tensor.device`

Tells us where the tensor is stored, such as CPU or GPU.

These properties are extremely useful when debugging neural networks.

In [11]:
x = torch.tensor([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])

print("Tensor:")
print(x)

print("\nShape:", x.shape)
print("Dimensions:", x.ndim)
print("Number of elements:", x.numel())
print("Data type:", x.dtype)
print("Device:", x.device)

Tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Shape: torch.Size([2, 3])
Dimensions: 2
Number of elements: 6
Data type: torch.float32
Device: cpu


# 7. Creating Tensors

PyTorch provides many functions for creating tensors.

Some of the most commonly used are:

- `torch.tensor()`
- `torch.zeros()`
- `torch.ones()`
- `torch.rand()`
- `torch.randn()`
- `torch.arange()`
- `torch.linspace()`

We will examine them one by one.

## 7.1 Creating a Tensor Manually

 We can create tensors directly using:

 `torch.tensor()`

In [12]:
x = torch.tensor([1, 2, 3, 4, 5])

print(x)

tensor([1, 2, 3, 4, 5])


## 7.2 Creating Tensors Filled With Zeros

`torch.zeros()` creates a tensor where every value is zero.

We provide the desired shape.

In [13]:
zeros = torch.zeros(3, 4)

print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [14]:
print("Shape:", zeros.shape)
print("Data type:", zeros.dtype)

Shape: torch.Size([3, 4])
Data type: torch.float32


## 7.3 Creating Tensors Filled With Ones

`torch.ones()` creates a tensor where every value is one.

In [15]:
ones = torch.ones(2, 5)

print(ones)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [16]:
print("Shape:", ones.shape)
print("Number of elements:", ones.numel())

Shape: torch.Size([2, 5])
Number of elements: 10


## 7.4 Random Tensors

Random tensors are extremely important in deep learning.

Neural-network weights are often initialized using random values.

`torch.rand()` creates random numbers between approximately 0 and 1.

In [17]:
random_tensor = torch.rand(3, 4)

print(random_tensor)

tensor([[0.3465, 0.6687, 0.0311, 0.8421],
        [0.5148, 0.7961, 0.6706, 0.1699],
        [0.0148, 0.8758, 0.1784, 0.9279]])


In [18]:
print("Shape:", random_tensor.shape)

print("Dimensions:", random_tensor.ndim)

Shape: torch.Size([3, 4])
Dimensions: 2


## 7.5 Normally Distributed Random Numbers

`torch.randn()` creates random values sampled approximately from a standard normal distribution.

A standard normal distribution has approximately:

- Mean = 0
- Standard deviation = 1

This function is commonly used when initializing neural-network parameters.

In [19]:
normal_tensor = torch.randn(3, 4)

print(normal_tensor)

tensor([[ 0.4496, -2.0989, -0.0825,  0.3335],
        [ 0.3551,  1.6429, -0.7707,  0.0461],
        [ 0.9288, -1.1009,  0.4420,  0.8741]])


## 7.6 Creating a Sequence With `torch.arange()`

`torch.arange()` creates a sequence of values.

It is similar to Python's `range()`.

In [20]:
numbers = torch.arange(0, 10)

print(numbers)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [21]:
even_numbers = torch.arange(0, 10, 2)

print(even_numbers)

tensor([0, 2, 4, 6, 8])


In [22]:
even_numbers = torch.arange(0, 10, 2.5)

print(even_numbers)

tensor([0.0000, 2.5000, 5.0000, 7.5000])


The arguments are approximately:

`torch.arange(start, stop, step)`

For example:

`torch.arange(0, 10, 2)`

means:

- Start at 0
- Stop before 10
- Increase by 2

## 7.7 Creating Evenly Spaced Values With `torch.linspace()`

`torch.linspace()` creates a specific number of equally spaced values between a starting and ending value.

In [23]:
values = torch.linspace(0, 1, 5)
print(values)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


The result contains 5 equally spaced values from 0 to 1.

The important difference is:

### `torch.arange()`

Usually controls the **step size**.

### `torch.linspace()`

Controls the **number of values**.

# 8. Creating Tensors With the Same Shape

Sometimes we already have a tensor and want to create another tensor with the same shape.

PyTorch provides functions such as:

- `torch.zeros_like()`
- `torch.ones_like()`
- `torch.rand_like()`

In [24]:
x = torch.tensor([ [1, 2, 3], [4, 5, 6] ])
print("Original tensor:")
print(x)
print("\nZeros with same shape:")
print(torch.zeros_like(x))
print("\nOnes with same shape:")
print(torch.ones_like(x))

Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Zeros with same shape:
tensor([[0, 0, 0],
        [0, 0, 0]])

Ones with same shape:
tensor([[1, 1, 1],
        [1, 1, 1]])


# 9. Tensor Data Types

Every tensor has a data type.

The data type determines how the numbers inside the tensor are stored.

Some common PyTorch data types are:

$$
\begin{array}{|c|c|}
\hline
\textbf{Data Type} & \textbf{Meaning} \\
\hline
\texttt{torch.float32} & \text{32-bit floating point} \\
\hline
\texttt{torch.float64} & \text{64-bit floating point} \\
\hline
\texttt{torch.float16} & \text{16-bit floating point} \\
\hline
\texttt{torch.int64} & \text{64-bit integer} \\
\hline
\texttt{torch.int32} & \text{32-bit integer} \\
\hline
\texttt{torch.bool} & \text{Boolean} \\
\hline
\end{array}
$$

In deep learning, `torch.float32` is extremely common.

In [25]:
integer_tensor = torch.tensor([1, 2, 3])
float_tensor = torch.tensor([1.0, 2.0, 3.0])
print("Integer tensor dtype:", integer_tensor.dtype)
print("Float tensor dtype:", float_tensor.dtype)

Integer tensor dtype: torch.int64
Float tensor dtype: torch.float32


Notice something important:

When we use:

[1, 2, 3]

PyTorch interprets the values as integers.

When we use:

[1.0, 2.0, 3.0]

PyTorch interprets them as floating-point values.

## Specifying the Data Type Manually

We can explicitly tell PyTorch which data type we want.

In [26]:
x = torch.tensor(
    [1, 2, 3],
    dtype=torch.float32
)
print(x)
print("Data type:", x.dtype)

tensor([1., 2., 3.])
Data type: torch.float32


## Changing a Tensor's Data Type

We can convert an existing tensor to another data type.

For example:

- `.float()`
- `.double()`
- `.long()`
- `.bool()`

In [27]:
x = torch.tensor([1, 2, 3])
print("Before conversion:", x.dtype)
x = x.float()
print("After conversion:", x.dtype)

Before conversion: torch.int64
After conversion: torch.float32


# 10. Tensor Device

PyTorch tensors can be stored and processed on different hardware devices.

The two most common are:

- CPU
- GPU

 The GPU can dramatically accelerate many deep-learning operations.

In [28]:
x = torch.tensor([1, 2, 3])
print("Tensor device:", x.device)

Tensor device: cpu


## Checking for a GPU in Google Colab

Google Colab can provide access to a GPU.

We can check whether PyTorch can access one using:

`torch.cuda.is_available()`

In [29]:
print("CUDA available:", torch.cuda.is_available())

CUDA available: False


In [30]:
if torch.cuda.is_available():
  print("GPU:", torch.cuda.get_device_name(0))
else:
  print("Currently using CPU")

Currently using CPU


## Creating a Device Variable

A common PyTorch pattern is to automatically choose the GPU when one is available.

Otherwise, we use the CPU.

In [31]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Using device:", device)

Using device: cpu


## Moving a Tensor to the Device

We can move tensors using:

`.to(device)`

In [32]:
x = torch.tensor([1.0, 2.0, 3.0])
x = x.to(device)
print(x)
print("Device:", x.device)

tensor([1., 2., 3.])
Device: cpu


### Important Rule

Tensors participating in the same operation usually need to be on the same device.

For example, this will create problems:

- Model → GPU
- Input tensor → CPU

Later, when training neural networks, we will normally move both the model and the data to the same device.

# 11. Random Seeds

Whenever we create random tensors, the values normally change each time we run the code.

For experiments, we sometimes want the same random numbers every time.

This is called **reproducibility**.

PyTorch allows us to control randomness using a random seed.

In [35]:
print(torch.rand(5))

tensor([0.6009, 0.2566, 0.7936, 0.9408, 0.1332])


In [36]:
torch.manual_seed(42)
x = torch.rand(5)
print(x)

tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904])


In [37]:
torch.manual_seed(42)
y = torch.rand(5)
print(y)

tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904])


Because we used the same seed before generating both tensors, the generated values should be identical.

Random seeds become very important when we want our machine-learning experiments to be reproducible.

# 12. Understanding Tensor Shapes in Deep Learning

One of the most important skills in PyTorch is understanding tensor shapes.

Consider a batch of RGB images:

[32, 3, 224, 224]

In PyTorch image processing, this usually means:

- 32 → Number of images in the batch
- 3 → Number of channels
- 224 → Image height
- 224 → Image width

This format is commonly written as:

N × C × H × W

where:

- N = Batch size
- C = Channels
- H = Height
- W = Width

In [39]:
images = torch.randn(32, 3, 224, 224)
print("Shape:", images.shape)
print("Dimensions:", images.ndim)

Shape: torch.Size([32, 3, 224, 224])
Dimensions: 4


## Example: Grayscale Ultrasound Images

Most ultrasound images can be represented as single-channel images.

Suppose we have:

16 ultrasound images

Each image is:

256 × 256 pixels

Because the images are grayscale, we have: 1 channel

Therefore the tensor shape can be:

[16, 1, 256, 256]

In [40]:
ultrasound_images = torch.randn(16, 1, 256, 256)
print("Shape:", ultrasound_images.shape)
print("Dimensions:", ultrasound_images.ndim)
print("Number of elements:", ultrasound_images.numel())

Shape: torch.Size([16, 1, 256, 256])
Dimensions: 4
Number of elements: 1048576


Interpretation:

[16, 1, 256, 256]

means:

- 16 → Images
- 1 → Channel
- 256 → Height
- 256 → Width

Later, tensors with this structure can be passed into convolutional neural networks.

# 13. Tensor Debugging Habit

Whenever a tensor causes an error, one of the first things we should inspect is:

- Shape
- Number of dimensions
- Data type
- Device
- Number of elements

This simple debugging habit solves many PyTorch problems.

In [41]:
x = torch.randn(8, 3, 64, 64)
print("Shape:", x.shape)
print("Dimensions:", x.ndim)
print("Data type:", x.dtype)
print("Device:", x.device)
print("Number of elements:", x.numel())

Shape: torch.Size([8, 3, 64, 64])
Dimensions: 4
Data type: torch.float32
Device: cpu
Number of elements: 98304


# 14. Practice Exercises

Try solving these exercises without looking at the previous code first.

 ---

 ## Exercise 1

Create a tensor containing:

[10, 20, 30, 40, 50]

Print:

- Tensor
- Shape
- Number of dimensions
- Number of elements
- Data type

---

## Exercise 2

Create a tensor of zeros with shape:

[3, 4]

Then print its shape.

---

## Exercise 3

Create a tensor of ones with shape:

[2, 3, 4]

Before running the code, predict:

- Number of dimensions
- Number of elements

---

## Exercise 4

Create a random tensor with shape:

[5, 3]

Print:

- Shape
- dtype
- device

---

## Exercise 5

Create the sequence:

0, 2, 4, 6, 8

using `torch.arange()`.

 ---

## Exercise 6

Create 10 equally spaced values between 0 and 1 using `torch.linspace()`.

---

## Exercise 7

Create a tensor:

[1, 2, 3]

Convert it from integer to `float32`.

---

## Exercise 8

Create a fake batch of grayscale images with:

- Batch size = 8
- Channels = 1
- Height = 128
- Width = 128

What should its shape be?

# 15. Shape Reasoning Challenge

Do not run Python immediately.

Try predicting the answers first.

---

### Question 1

A tensor has shape:

[5]

How many dimensions does it have?

---

### Question 2

A tensor has shape:

[4, 6]

How many elements does it contain?

---
### Question 3

A tensor has shape:

[2, 3, 4]

How many dimensions does it have?

How many total values does it contain?

---

### Question 4

A tensor representing RGB images has shape:

[64, 3, 224, 224]

Answer:

1. What is the batch size?
2. How many channels?
3. What is the height?
4. What is the width?
5. Is this likely RGB or grayscale?

---

### Question 5

A batch of ultrasound images has shape:

[32, 1, 256, 256]

Explain what every dimension means.

# 16. Key Takeaways

In this notebook, we learned the fundamental ideas behind PyTorch tensors.

A tensor is a multidimensional container for numbers.

The most important tensor properties are:

- `shape`
- `ndim`
- `numel()`
- `dtype`
- `device`

We also learned how to create tensors using:

- `torch.tensor()`
- `torch.zeros()`
- `torch.ones()`
- `torch.rand()`
- `torch.randn()`
- `torch.arange()`
- `torch.linspace()`

One of the most important habits in PyTorch is:

> Always understand what every dimension of your tensor represents.

For example:

[32, 3, 224, 224]

means:

32 images × 3 channels × 224 height × 224 width.


# 17. Check Your Understanding

Before moving to the next notebook, make sure you can answer these questions without searching:

1. What is a tensor?
2. What is a scalar?
3. What is a vector?
4. What is a matrix?
5. What does `shape` tell us?
6. What does `ndim` tell us?
7. What does `numel()` tell us?
8. What is `dtype`?
9. What is `device`?
10. What does `torch.rand()` do?
11. What is the difference between `torch.rand()` and `torch.randn()`?
12. What does `[32, 3, 224, 224]` mean for image data?
13. Why are tensor shapes important in deep learning?
14. Why do CPU and GPU devices matter?
15. Why might we use a random seed?

If you can explain these clearly in your own words, your tensor fundamentals are developing correctly.
